/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ArchitectureRouteImport } from './routes/architecture'
import { Route as McpRouteImport } from './routes/mcp'
import { Route as ApiChatRouteImport } from './routes/api/chat'
import { Route as CompaniesNameRouteImport } from './routes/companies/$name'
import { Route as ProductsIndexRouteImport } from './routes/products/index'
import { Route as SubstancesIdentifierRouteImport } from './routes/substances/$identifier'
import { Route as ProductsCountryIdRouteImport } from './routes/products/$country/$id'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ArchitectureRoute = ArchitectureRouteImport.update({
  id: '/architecture',
  path: '/architecture',
  getParentRoute: () => rootRouteImport,
} as any)
const McpRoute = McpRouteImport.update({
  id: '/mcp',
  path: '/mcp',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiChatRoute = ApiChatRouteImport.update({
  id: '/api/chat',
  path: '/api/chat',
  getParentRoute: () => rootRouteImport,
} as any)
const CompaniesNameRoute = CompaniesNameRouteImport.update({
  id: '/companies/$name',
  path: '/companies/$name',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductsIndexRoute = ProductsIndexRouteImport.update({
  id: '/products/',
  path: '/products/',
  getParentRoute: () => rootRouteImport,
} as any)
const SubstancesIdentifierRoute = SubstancesIdentifierRouteImport.update({
  id: '/substances/$identifier',
  path: '/substances/$identifier',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductsCountryIdRoute = ProductsCountryIdRouteImport.update({
  id: '/products/$country/$id',
  path: '/products/$country/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/architecture': typeof ArchitectureRoute
  '/mcp': typeof McpRoute
  '/api/chat': typeof ApiChatRoute
  '/companies/$name': typeof CompaniesNameRoute
  '/substances/$identifier': typeof SubstancesIdentifierRoute
  '/products/': typeof ProductsIndexRoute
  '/products/$country/$id': typeof ProductsCountryIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/architecture': typeof ArchitectureRoute
  '/mcp': typeof McpRoute
  '/api/chat': typeof ApiChatRoute
  '/companies/$name': typeof CompaniesNameRoute
  '/substances/$identifier': typeof SubstancesIdentifierRoute
  '/products': typeof ProductsIndexRoute
  '/products/$country/$id': typeof ProductsCountryIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/architecture': typeof ArchitectureRoute
  '/mcp': typeof McpRoute
  '/api/chat': typeof ApiChatRoute
  '/companies/$name': typeof CompaniesNameRoute
  '/substances/$identifier': typeof SubstancesIdentifierRoute
  '/products/': typeof ProductsIndexRoute
  '/products/$country/$id': typeof ProductsCountryIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/architecture'
    | '/mcp'
    | '/api/chat'
    | '/companies/$name'
    | '/substances/$identifier'
    | '/products/'
    | '/products/$country/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/architecture'
    | '/mcp'
    | '/api/chat'
    | '/companies/$name'
    | '/substances/$identifier'
    | '/products'
    | '/products/$country/$id'
  id:
    | '__root__'
    | '/'
    | '/architecture'
    | '/mcp'
    | '/api/chat'
    | '/companies/$name'
    | '/substances/$identifier'
    | '/products/'
    | '/products/$country/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ArchitectureRoute: typeof ArchitectureRoute
  McpRoute: typeof McpRoute
  ApiChatRoute: typeof ApiChatRoute
  CompaniesNameRoute: typeof CompaniesNameRoute
  SubstancesIdentifierRoute: typeof SubstancesIdentifierRoute
  ProductsIndexRoute: typeof ProductsIndexRoute
  ProductsCountryIdRoute: typeof ProductsCountryIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/architecture': {
      id: '/architecture'
      path: '/architecture'
      fullPath: '/architecture'
      preLoaderRoute: typeof ArchitectureRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mcp': {
      id: '/mcp'
      path: '/mcp'
      fullPath: '/mcp'
      preLoaderRoute: typeof McpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/chat': {
      id: '/api/chat'
      path: '/api/chat'
      fullPath: '/api/chat'
      preLoaderRoute: typeof ApiChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/companies/$name': {
      id: '/companies/$name'
      path: '/companies/$name'
      fullPath: '/companies/$name'
      preLoaderRoute: typeof CompaniesNameRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/products/': {
      id: '/products/'
      path: '/products'
      fullPath: '/products/'
      preLoaderRoute: typeof ProductsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/substances/$identifier': {
      id: '/substances/$identifier'
      path: '/substances/$identifier'
      fullPath: '/substances/$identifier'
      preLoaderRoute: typeof SubstancesIdentifierRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/products/$country/$id': {
      id: '/products/$country/$id'
      path: '/products/$country/$id'
      fullPath: '/products/$country/$id'
      preLoaderRoute: typeof ProductsCountryIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ArchitectureRoute: ArchitectureRoute,
  McpRoute: McpRoute,
  ApiChatRoute: ApiChatRoute,
  CompaniesNameRoute: CompaniesNameRoute,
  SubstancesIdentifierRoute: SubstancesIdentifierRoute,
  ProductsIndexRoute: ProductsIndexRoute,
  ProductsCountryIdRoute: ProductsCountryIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
